version: "3.4"

services:
  backend:
    container_name: gitbackup_backend
    env_file: .env
    environment:
      - DEBUGPY=${DEBUGPY}
    user: ${CURRENT_UID}
    build:
      context: .
      args:
        - DEBUG=${DEBUG}
      target: deploy
    restart: on-failure
    volumes:
      - ./static:/app/static/
      - gitbackup_media:/app/media/
      - .:/app/
    ports:
      - 8000:8000
    networks:
      # proxy:
      private_network:
        ipv4_address: 172.16.0.8

  backend-dev:
    container_name: gitbackup_backend_dev
    env_file: .env
    environment:
      - DEBUGPY=${DEBUGPY}
    user: ${CURRENT_UID}
    build:
      context: .
      args:
        - DEBUG=${DEBUG}
      target: deploy
    restart: on-failure
    volumes:
      - .:/app/
    ports:
      - 5678:5678
      - 8000:8000
    networks:
      private_network:
        ipv4_address: 172.16.0.5

  postgres:
    container_name: gitbackup_postgres
    env_file: .env
    image: postgres:12.3-alpine
    restart: on-failure
    volumes:
      - gitbackup_db_data:/var/lib/postgresql/data
      - gitbackup_db_backups:/var/backups
    networks:
      private_network:
        ipv4_address: 172.16.0.6

  qcluster:
    image: gitbackup_backend
    container_name: gitbackup_qcluster
    env_file: .env
    user: ${CURRENT_UID}
    volumes:
      - ./static:/app/static/
      - gitbackup_media:/app/media/
      - .:/app/
    restart: on-failure
    entrypoint: python3
    command: ./manage.py qcluster
    depends_on:
      - backend
    networks:
      private_network:
        ipv4_address: 172.16.0.7

  qcluster-dev:
    image: gitbackup_backend-dev
    container_name: gitbackup_qcluster_dev
    env_file: .env
    user: ${CURRENT_UID}
    volumes:
      - .:/app/
    restart: on-failure
    entrypoint: python3
    command: ./manage.py qcluster
    networks:
      private_network:
        ipv4_address: 172.16.0.9

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16

volumes:
  gitbackup_db_data:
    external: true
  gitbackup_media:
    external: true
  gitbackup_db_backups:
    external: true
