# Generated by Django 3.1.4 on 2020-12-22 11:18

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('token', models.CharField(blank=True, max_length=150, null=True, verbose_name='token')),
                ('private', models.BooleanField(default=False, verbose_name='private')),
                ('url', models.URLField(max_length=250, verbose_name='url')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='comment')),
            ],
            options={
                'verbose_name': 'репозиторий',
                'verbose_name_plural': 'репозитории',
            },
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastrunned', models.DateTimeField(editable=False, verbose_name='lastrunned')),
                ('taskname', models.CharField(max_length=50, verbose_name='taskname')),
            ],
            options={
                'verbose_name': 'запуск',
                'verbose_name_plural': 'запуски',
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.get_file_path, verbose_name='backup')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.repo')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.taskmodel')),
            ],
            options={
                'verbose_name': 'бэкап',
                'verbose_name_plural': 'бэкапы',
            },
        ),
    ]
