# Generated by Django 3.1.4 on 2020-12-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='args',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='returncode',
            field=models.IntegerField(default=0, verbose_name='returncode'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='stderr',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='stdout',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='successful',
            field=models.BooleanField(default=True, editable=False, verbose_name='successful'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='taskname',
            field=models.CharField(editable=False, max_length=50, verbose_name='taskname'),
        ),
    ]
