# Generated by Django 3.1.4 on 2020-12-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='repo',
            name='token',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='token'),
        ),
    ]
