# Generated by Django 3.1.4 on 2020-12-25 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201223_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.repo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.taskmodel'),
        ),
    ]
